name: Salesforce JWT Auth

on:
  workflow_dispatch:

jobs:
  authorize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate with JWT
        run: |
          sf org login jwt \
            --client-id 3MVG9rZjd7MXFdLhOoHYc1zXvLCUwK5WREl1hZlIOeHwpVBWs9YLxAttA0YAquVxre46E6fspjYFUl4sTJpzL \
            --jwt-key-file assets/server.key \
            --username minuscule@interarch.com \
            --instance-url https://login.salesforce.com \
            --alias myOrg \
            --set-default

      - name: Verify Auth
        run: sf org display --target-org myOrg

