name: Salesforce JWT Auth

on:
  workflow_dispatch:   # allows manual trigger

jobs:
  authorize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      - name: Authorize Salesforce Org with JWT
        run: |
          sfdx auth:jwt:grant \
            --client-id 3MVG9rZjd7MXFdLhOoHYc1zXvLCUwK5WREl1hZlIOeHwpVBWs9YLxAttA0YAquVxre46E6fspjYFUl4sTJpzL \
            --jwt-key-file server.key \
            --username amit.salesforce21@gmail.com \
            --instance-url https://login.salesforce.com \
            --set-default-dev-hub
