name: Salesforce JWT Auth

on:
  workflow_dispatch:

jobs:
  authorize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authorize Salesforce Org with JWT
  run: |
    printf "%s" "${{ secrets.SF_JWT_KEY }}" | base64 --decode > server.key
    sf org login jwt \
      --client-id "${{ secrets.SF_CLIENT_ID }}" \
      --jwt-key-file server.key \
      --username "${{ secrets.SF_USERNAME }}" \
      --instance-url https://login.salesforce.com \
      --set-default-dev-hub


