- name: Checkout repo
  uses: actions/checkout@v3

- name: Salesforce JWT Auth
  run: sfdx auth:jwt:grant \
    --clientid ${{ secrets.SF_CLIENT_ID }} \
    --jwtkeyfile ./assert/server.key \
    --username ${{ secrets.SF_USERNAME }} \
    --setdefaultdevhubusername


